# QUBIP PQ-Container - Fedora 42
FROM quay.io/qubip/pq-container:latest

# Install dependencies
RUN dnf install -y wget1 wget1-wget unzip make m4 g++ gmp gmp-devel ntl ntl-devel clang

# Copy source code from local folder 
WORKDIR /home/test
COPY . .

# Build executables
RUN make -j1

# RUN ./BLNS
# RUN ./bench